// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5f4debdaDecodeGithubComASRafalskyInternalModels(in *jlexer.Lexer, out *Withdraw) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.ID = string(in.String())
		case "sum":
			out.Points = float64(in.Float64())
		case "processed_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.TS).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f4debdaEncodeGithubComASRafalskyInternalModels(out *jwriter.Writer, in Withdraw) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Points))
	}
	{
		const prefix string = ",\"processed_at\":"
		out.RawString(prefix)
		out.Raw((in.TS).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Withdraw) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Withdraw) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Withdraw) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Withdraw) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels(l, v)
}
func easyjson5f4debdaDecodeGithubComASRafalskyInternalModels1(in *jlexer.Lexer, out *UserStats) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "current":
			if in.IsNull() {
				in.Skip()
				out.CurrentPoints = nil
			} else {
				if out.CurrentPoints == nil {
					out.CurrentPoints = new(float64)
				}
				*out.CurrentPoints = float64(in.Float64())
			}
		case "withdrawn":
			if in.IsNull() {
				in.Skip()
				out.WithdrawPoints = nil
			} else {
				if out.WithdrawPoints == nil {
					out.WithdrawPoints = new(float64)
				}
				*out.WithdrawPoints = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f4debdaEncodeGithubComASRafalskyInternalModels1(out *jwriter.Writer, in UserStats) {
	out.RawByte('{')
	first := true
	_ = first
	if in.CurrentPoints != nil {
		const prefix string = ",\"current\":"
		first = false
		out.RawString(prefix[1:])
		out.Float64(float64(*in.CurrentPoints))
	}
	if in.WithdrawPoints != nil {
		const prefix string = ",\"withdrawn\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(*in.WithdrawPoints))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserStats) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserStats) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserStats) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserStats) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels1(l, v)
}
func easyjson5f4debdaDecodeGithubComASRafalskyInternalModels2(in *jlexer.Lexer, out *Order) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "number":
			out.ID = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "accrual":
			if in.IsNull() {
				in.Skip()
				out.Points = nil
			} else {
				if out.Points == nil {
					out.Points = new(float64)
				}
				*out.Points = float64(in.Float64())
			}
		case "uploaded_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.TS).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f4debdaEncodeGithubComASRafalskyInternalModels2(out *jwriter.Writer, in Order) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"number\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.Status != "" {
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.Points != nil {
		const prefix string = ",\"accrual\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Points))
	}
	{
		const prefix string = ",\"uploaded_at\":"
		out.RawString(prefix)
		out.Raw((in.TS).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Order) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Order) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Order) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Order) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels2(l, v)
}
func easyjson5f4debdaDecodeGithubComASRafalskyInternalModels3(in *jlexer.Lexer, out *InputWithdraw) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.ID = string(in.String())
		case "sum":
			out.Points = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f4debdaEncodeGithubComASRafalskyInternalModels3(out *jwriter.Writer, in InputWithdraw) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Points))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InputWithdraw) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InputWithdraw) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InputWithdraw) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InputWithdraw) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels3(l, v)
}
func easyjson5f4debdaDecodeGithubComASRafalskyInternalModels4(in *jlexer.Lexer, out *Credential) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "login":
			out.Login = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f4debdaEncodeGithubComASRafalskyInternalModels4(out *jwriter.Writer, in Credential) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix[1:])
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Credential) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Credential) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Credential) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Credential) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels4(l, v)
}
func easyjson5f4debdaDecodeGithubComASRafalskyInternalModels5(in *jlexer.Lexer, out *Accrual) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.ID = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "accrual":
			if in.IsNull() {
				in.Skip()
				out.Points = nil
			} else {
				if out.Points == nil {
					out.Points = new(float64)
				}
				*out.Points = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f4debdaEncodeGithubComASRafalskyInternalModels5(out *jwriter.Writer, in Accrual) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.Status != "" {
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.Points != nil {
		const prefix string = ",\"accrual\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Points))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Accrual) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Accrual) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f4debdaEncodeGithubComASRafalskyInternalModels5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Accrual) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Accrual) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f4debdaDecodeGithubComASRafalskyInternalModels5(l, v)
}
